# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='date_of_friendship',
            field=models.DateTimeField(null=True),
        ),
    ]
