# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20171104_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_making_request', to='basic_app.Profile')),
                ('requestTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_request_to', to='basic_app.Profile')),
            ],
        ),
    ]
