# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20171123_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=10000)),
                ('pub_date', models.DateTimeField()),
                ('messageFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_from', to='basic_app.Profile')),
                ('messageTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_to', to='basic_app.Profile')),
            ],
        ),
    ]
