# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20171205_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=1000)),
                ('notification_by_email', models.CharField(max_length=2000)),
                ('notification_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for', to='basic_app.Profile')),
            ],
        ),
    ]
