# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20180218_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=b'media')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_file', to='basic_app.Group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by_file', to='basic_app.Profile')),
            ],
        ),
    ]
