# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_groupfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile_pic',
            field=models.ImageField(default=b'pic_folder/no_pic_grp.png', upload_to=b'pic_folder/'),
        ),
    ]
