# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_group_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
