# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_auto_20180218_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default=b'pic_folder/no_pic_grp.png', upload_to=b'media'),
        ),
    ]
