# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0024_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='account_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
