# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0025_tempuser_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1000)),
                ('exam_type', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Profile')),
            ],
        ),
    ]
