# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0027_forgotpwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_photo_directory',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='photo_links',
            name='which_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Post'),
        ),
    ]
