# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0028_auto_20180330_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
